Repository RP-StarHub/Front-end, pull requests merged in 2025-02, with the labels that each got.

#37 [PR] Feat: 마이페이지 UI 구현 및 API 연결
  src/App.tsx
  src/assets/data/mypageData.js
  src/components/common/layout/Navbar.tsx
  src/components/main/InformCard.tsx
  src/components/mypage/MeetingListLayout.tsx
  src/components/mypage/MyProfile.tsx
  src/components/mypage/RecentMeetingSection.tsx
  src/hooks/api/useLike.ts
  src/hooks/api/useMypage.ts
  src/pages/mypage/AppliedMeetingsPage.tsx
  src/pages/mypage/CreatedMeetingsPage.tsx
  src/pages/mypage/LikedMeetingsPage.tsx
  src/pages/mypage/MainMyPage.tsx
  src/pages/mypage/ProfileEditPage.tsx
  src/services/api/mypage.ts
  src/types/api/meeting.ts
  src/types/api/mypage.ts
  src/types/models/common.ts
  src/types/models/meeting.ts
Labels: :recycle: Refactor, :sparkles: Feat, 📬 API, 🎨 Style

#41 [PR] Refactor: 네이버지도로 마이그레이션
  package-lock.json
  package.json
  public/index.html
  src/components/main/EventMarker.tsx
  src/components/main/OverCard.tsx
  src/pages/MainPage.tsx
  src/pages/meeting/CreateMeetingBasicPage.tsx
Labels: :recycle: Refactor, :sparkles: Feat

#42 [PR] Design: 푸터 변경 및 반응형 추가
  public/index.html
  src/App.tsx
  src/components/common/layout/Footer.tsx
  src/components/main/StudyList.tsx
  src/pages/MainPage.tsx
  src/pages/Signup.tsx
  src/services/api/axios.ts
Labels: 🎨 Style
